# Generated by Django 4.2.4 on 2023-11-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
